apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: jobtimer-scheduler
    tier: api
  name: jobtimer-scheduler
spec:
  replicas: 1
  selector:
    app: jobtimer-scheduler
    tier: api
  template:
    metadata:
      labels:
        app: jobtimer-scheduler
        tier: api
    spec:
      containers:
      - name: jobtimer-scheduler
        env:
        - name: KUBE_NAMESPACE
          value: jobtimer
        image: paralin/job-timer-scheduler:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
          name: web
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
