apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobtimer-scheduler
    tier: api
  name: jobtimer-scheduler
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: jobtimer-scheduler
    tier: api
  type: LoadBalancer
